notifications:
  email: false
git:
  quiet: true
  depth: false
env:
  global:
  - TERM=dumb
  - secure: "wZNiwKeRWd1mSrwCJw37Vu2hkoOyRBA8dcvW3pDsZQXrRYanQIVfJ+BllC3b/p5g6u7Vcmn5PuI9sTG9+0RiyPzbypn4J8uNEoVexi48lVYn4QkRdp8UTMLb4qovA28cMZDuUU7yE3yHJWXoAlTfMybyLTM0jq0xUogtV0y+MWRkCKUy2ijFi3yKiIX/hroinh8VJN1ecJh/atxnGMghZu1ijWdqt8EHaQ0yG9q/f8Jyn2qPxYLYuR02Woloe+8xoqUNWqFzs0Ul9+A88Kt6KutrevgK5arPfJ0TFcrRTYnHSrH5Zde7b44LOymoiI+IftspFMDWMWjtUHeDjPRjKr27egCbins+y2POUdGBt1wVePJYqXJM7NcB8aAJjqy/59nqK3f34Aeq5dMX2T+jSEyMgA6rXo9t7vvQRMtABiKjQI9Gse3gu5FwGejwAZyupDV1QLMkI179KMzx51gJ/dOTk2k+sCvDwYbZAlSYZzzRZCPI1lQvIm8oIECH81iKKZDgsFZSGJrYOcdZUJ1QM+T7WOKJOqb3yCr88bDxkg+aAKb4IRT0kbJe819In43F/cIpvfNga9M6VTqzkMhjcTZwYqulvDzCKS9GqIO0Hlqjjzp2g3vxcQ2W5eDCUvfobZHLTTXyBCx1o50miWmcri6YslDRkDm0fhNNN6j5VBE="
language: python
python:
- "3.7"
matrix:
  include:
  - python: "3.7"
addons:
  apt:
    update: true
install: true
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip install --upgrade pip
- pip install --upgrade mkdocs mkdocs-material mkdocs-minify-plugin
cache:
  pip: true
  packages: true
  directories:
  - ~/.local
stages:
- deploy
jobs:
  include:
  - stage: deploy
    name: Deploy VuePress documentation on GitHub Pages openjdk8
    #if: branch ~= /master/ AND (type NOT IN (pull_request))
    #if: tag IS present
    python: 3.7
    script: skip
    before_deploy:
    - mkdocs build
    deploy:
    - provider: pages
      skip-cleanup: true
      keep-history: true
      target_branch: gh-pages
      # travis encrypt GITHUB_TOKEN=<your github repo token> --add
      github-token: "$GITHUB_TOKEN"
      local-dir: ./site
      #on:
      #  tags: true
