notifications:
  email: false
git:
  quiet: true
  depth: false
env:
  global:
  - TERM=dumb
language: python
python: 3
services: docker
addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - curl
    - python3-dev
    - python3-pip
    - python3-six
    - libxml2-utils
    - python3-setuptools
install: true
before_install:
#- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- |
  if [ ! -f $HOME/.local/daggerok/bash-functions/master/main.bash ] ; then
    mkdir -p $HOME/.local/daggerok/bash-functions/master ;
    curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > $HOME/.local/daggerok/bash-functions/master/main.bash ;
  fi
  source $HOME/.local/daggerok/bash-functions/master/main.bash ;
- stop_any 80 8080 9000
- export PATH=$HOME/.local/bin:$PATH
- $(which pip3) install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- $(which pip3) install --user $(whoami) --upgrade pip >/dev/null
- $(which pip3) install --user $(whoami) --upgrade mkdocs mkdocs-material mkdocs-minify-plugin >/dev/null
cache:
  pip: true
  packages: true
  directories:
  - ~/.local/bin
stages:
- deploy
jobs:
  include:
  - stage: deploy
    name: Deploy VuePress documentation on GitHub Pages openjdk8
    ##if: branch ~= /master/ AND (type NOT IN (pull_request))
    #if: tag IS present
    script: skip
    before_deploy:
    - mkdocs build
    deploy:
    - provider: pages
      skip-cleanup: true
      keep-history: true
      target_branch: gh-pages
      github-token: "$GITHUB_TOKEN"
      # travis encrypt GITHUB_TOKEN=<your github repo token> --add
      local-dir: ./site
      on:
        tags: true
